version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm

  test:
    docker:
      - image: cimg/node:16.10

    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Unit Tests
          command: npm test

workflows:
  sample:
    jobs:
      - build
#      - test
